CourseWork/CourseWork/Controllers/CardsController.cs
namespace CourseWork.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;

    using CourseWork.Common;
    using CourseWork.Data.Services;
    using CourseWork.ViewModels.Cards;

    public class CardsController : Controller
    {
        private readonly ICardsService service;

        public CardsController(ICardsService service)
        {
            this.service = service;
        }

        [Authorize]
        public IActionResult Add()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Add(CreateCardInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.service.CreateAsync(model);
            return this.RedirectToAction(nameof(this.All));
        }


        [Authorize]
        public IActionResult All(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 12;
            var viewModel = new CardsListViewModel()
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                CardsCount = this.service.GetCount(),
                Cards = this.service.GetAll<CardsInListViewModel>(id, ItemsPerPage),
            };
            return this.View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> AddToCollection(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            await this.service.AddCardToUserCollection(userId, id);

            return this.RedirectToAction(nameof(this.Collection));
        }

        [Authorize]
        public async Task<IActionResult> RemoveFromCollection(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            await this.service.RemoveCardFromUserCollection(id, userId);

            return this.RedirectToAction(nameof(this.All));
        }

        [Authorize]
        public IActionResult Collection()
        {
            //// var user = await this.userManager.GetUserAsync(this.User);
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var viewModel = this.service.GetById(userId);
            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var card = this.service.GetById<SingleCardViewModel>(id);
            return this.View(card);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult Edit(int id)
        {
            var inputModel = this.service.GetById<EditCardInputModel>(id);
            return this.View(inputModel);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Edit(int id, EditCardInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.service.UpdateAsync(id, input);
            return this.RedirectToAction(nameof(this.ById), new { id });
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task <IActionResult> Delete(int id)
        {
            await this.service.DeleteAsync(id);
            return this.RedirectToAction(nameof(this.All));
        }
    }
}

CourseWork/CourseWork/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->

    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/custom.css">

    <title>Personal cards collection</title>
</head>
<body class="container">
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-dark">
            <a class="nav-link text-white active h5" href="/">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="text-white">MENU</span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-white active h5" href="/Cards/All">All Cards</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white active h5" href="/Cards/Add">Add Card</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white active h5" href="/Cards/Collection">My Collection</a>
                        </li>
                    }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="bg-dark">
        <div class="container-fluid text-center">
            <small class="footer-background text-white">
                CopyRight &copy; Yu-Gi-Oh personal cards colleciton. All rights reserved.
            </small>
        </div>
    </footer>


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="/js/bootstrap.bundle.min.js"></script>
    <script src="/js/custom.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CourseWork/CourseWork/Views/Shared/_PagingPartial.cshtml
@model CourseWork.ViewModels.PagingViewModel
<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage) { <text> disabled </text>}">
            <a class="page-link" asp-controller="Cards" asp-action="All" asp-route-id="@Model.PreviousPageNumber">Previous</a>
        </li>
        @for (int i = Model.PageNumber - 3; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
<li class="page-item"><a class="page-link" asp-controller="Cards" asp-action="All" asp-route-id="@i">@i</a></li>}
            }
        <li class="page-item active">
            <span class="page-link">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 3; i++)
        {
            if (i <= Model.PagesCount)
            {
<li class="page-item"><a class="page-link" asp-controller="Cards" asp-action="All" asp-route-id="@i">@i</a></li>}
            }
        <li class="page-item @if (!Model.HasNextPage) { <text> disabled </text>}">
            <a class="page-link" asp-controller="Cards" asp-action="All" asp-route-id="@Model.NextPageNumber">Next</a>
        </li>
    </ul>
</nav>